on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn && yarn build

      - name: commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(build): build and package action" || true
          git push origin main

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Generate changelog and bump version
        id: changelog
        uses: ./
        with:
          bump-files: '**/package.json'
          extra-tags: |
            v{major}
            v{major}.{minor}

      - uses: softprops/action-gh-release@v1
        if: steps.changelog.outputs.released == 'true'
        id: release
        with:
          name: "Releaser ${{ steps.changelog.outputs.tag }}"
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.release_notes }}
